### ISSUE TITLE
Adding Notifications

### ISSUE THREAD

**Issue by togayyazar** [ENIAC-ETU/Photo_Album_Android#15]
Birisi paylaştığınız bir resmi beğendiğinde bu bilgi paylaşılan resmin kullanıcısına iletilmelidir. Web server bu bilgiyi android ile arasındaki iletişimden gönderebilmelidir.
Related to #5

**Comment by goksunonal** [comment]
[Subscribe To Django Notification Implementation Using Pusher](https://github.com/ENIAC-ETU/Photo_Album_Android/commit/79a0745a9146e40c161580e4c2b906b1e1ca931b)
[Adding Pusher and Firebase Implementation To Build](https://github.com/ENIAC-ETU/Photo_Album_Android/commit/5d654c3d7d89003d3b41aabe919f5bbd37840ab4)
[Adding Firebase to root build](https://github.com/ENIAC-ETU/Photo_Album_Android/commit/17277d240b170ef256e51406d0886e41c67bf5ee)
ile tamamlandı
